version: '3.7'
services:
  web:
    image: nginx
    restart: always
    ports:
      - "8082:8080"
    deploy:
      replicas: 2
  app: 
    image: tomcat:9-jdk8
    restart: always
    ports: 
    - "8081:8080"
    deploy:
      replicas: 3

