version: "3"
services:
  db:
    image: redis
    restart: always
    ports:
    - '8080:8080'
    container_name: redis-one
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - '8081:8080'
    container_name: tomcat
